### ISSUE TITLE
pragma message

### ISSUE THREAD

**Issue by travisdowns** [nemequ/portable-snippets#17]
Not sure in which module this would fit into, or if it's even interesting, but it would be nice to have portable ways of emitting messages at compile time, along the lines of what `gcc` offers with `#pragma message` since about the 4.4 version. I guess you'd have to emulate it with warnings before that?

**Comment by nemequ** [comment]
TBH I've never really seen much point in non-warning messages, but it seems like a reasonable request. It would probably be more appropriate to put it in [Hedley](https://github.com/nemequ/hedley), though.

Obviously it wouldn't be available *everywhere*, but MSVC also supports `#pragma message …`, as do clang icc, and probably armclang. OTOH, suncc, armcc, pgcc, and xlc don't.

Alas, falling back on `#warning …` isn't really possible since there is no way to generate it; `_Pragma("...")` maps to `#pragma ...` (or, for MSVC, there is `__pragma(...)`, but I know of no equivalent for `#warning`. AFAICT the fallback would have to be silence.

**Comment by travisdowns** [comment]
Yeah I was thinking Hedley might be the other place it makes sense: since the distinction is that Hedley is best effort: it tries to do what you want, but may fail silently (since it's "non functional" stuff) and psnip always does something (perhaps some portable fallback code), right?

The distinction between warning and "message" is pretty mushy. I just added a pragma message which is why I thought of this, but thinking about the use case, warning would also be suitable there (I was warning that `<regex>` wasn't supported on your compiler so some functionality would be disabled).

**Comment by nemequ** [comment]
> Yeah I was thinking Hedley might be the other place it makes sense: since the distinction is that Hedley is best effort: it tries to do what you want, but may fail silently (since it's "non functional" stuff) and psnip always does something (perhaps some portable fallback code), right?

Close. Hedley is restricted to stuff which, when there is no way to implement, still leaves the code working. For example, failing to inline a function leaves the code working, but failing to declare a variable as TLS is unlikely to end well.

For portable snippets it's okay (though obviously not optimal) if something fails, especially if it can be detected at runtime.

> The distinction between warning and "message" is pretty mushy. I just added a pragma message which is why I thought of this, but thinking about the use case, warning would also be suitable there (I was warning that <regex> wasn't supported on your compiler so some functionality would be disabled).

IIRC `#warning ...` isn't supported by MSVC, so `#pragma message ...` is probably the closest you're going to be able to get.

I'm going to close this here, I'll open up a new issue in Hedley.
