### ISSUE TITLE
Dependencies between components

### ISSUE THREAD

**Issue by travisdowns** [nemequ/portable-snippets#26]
@nemequ let's say I want to use a particular component of portable-snippets, say "clock" - is there some way to determine or pull to in all the modules that clock needs? I have tried the brute force approach of adding stuff until it compiles, and that is a bit annoying - but more importantly it doesn't seem reliable because the exact things a module depends on may depend on the platform: compile it somewhere else and it may want `atomic` when the original platform didn't.

Just throwing this out there to see if you have any thoughts.

I face this issue since for a small projects of 3 or 4 files, protable-snippets is still very useful but I don't want to bring in 20 files to make just `clock` work. It's still better than writing it myself though :).

**Comment by nemequ** [comment]
Not really.  I know this is a problem, and I guess all I could really do is document the dependencies in the README.  You're right, the conditional dependencies make this much more annoying.

Unfortunately the idea of single file libraries is kind of at odds with the idea of not repeating yourself.  I think the best solution would be to just build portable-snippets as a single static library, then rely on IPO to elide unused code.  That would also allow us to keep the build system logic in portable-snippets, which makes it a lot more feasible to use system libraries (e.g., librt and libpthread) when appropriate, since we wouldn't have to ask users to do any testing in their build system.  Of course, it would still be possible to continue using the code directly, and I'm sure some (most?) people would do that, so documenting dependencies would still be very useful.

Another option would be creating ways to pull in only specific modules by integrating with various build systems (autotools, cmake, meson, *etc.*).

**Comment by nemequ** [comment]
I believe 58347989ac65490b9dcdb13804e28e2f910f2adc largely fixes this.  The random module is still a bit of a problem, but I think everything else is about as good as I can get it.

I'm going to close this, but if you (or anyone) has any more ideas about how to further improve things please feel free to reopen or create a new issue.
