### ISSUE TITLE
"gnu" mode is needed for some modules like clock

### ISSUE THREAD

**Issue by travisdowns** [nemequ/portable-snippets#27]
Today I got all kinds of weird compile errors while building with `clock/clock.h`.

The underlying cause is that I had `-std=c11` on the compile command line, which means certainly POSIXY things not in C are not available, including `clock_gettime`.

As a simple solution maybe `clock` could error out in that case, with a message about needing gnu mode, rather than give the compiler errors.

More comprehensive fixes are possible, but none are necessarily perfect. For example, you could declare the required macros yourself, but this won't to work if `time.h` was already included by someone else earlier.

I worked around it by putting a `#define _GNU_SOURCE` prior to including `clock/clock.h`.

**Comment by nemequ** [comment]
Interesting I'll try to take a look tomorrow.

**Comment by travisdowns** [comment]
> Interesting, I'll try to take a look tomorrow.
> 
> This is with glibc, I assume? What version?

It's with glibc 2.23, although I don't think it matters: the man page is pretty clear:

```
   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       clock_getres(), clock_gettime(), clock_settime():
              _POSIX_C_SOURCE >= 199309L
```

And AFAIK `_POSIX_C_SOURCE` won't be defined by default with `-std=c*`, only with `-std=gnu*`. Note that `gcc` defaults to the `gnu` standards so you won't see this by default (but the whole point of portable snippets is to be portable and not rely on gnu features so it's a bit ironic :)).

**Comment by nemequ** [comment]
Just pushing out a work-around now, sorry about the delay.

It's not really a GNU feature, it's POSIX, and we check for `_POSIX_TIMERS` to indicate support for that particular API.  I guess it's an oversight in glibc that `_POSIX_TIMERS` would be defined even if POSIX support isn't supposed to be enabled.

Anyways, the point of portable snippets is largely to work around these types of issues.  Unfortunately we can't really just define `_POSIX_C_SOURCE` in the header because there is a good chance it's not soon enough.  I've added an additional check on `_POSIX_C_SOURCE` before enabling the `clock_gettime` API, even if `_POSIX_TIMERS` is defined, as well as a note in the README.
