### ISSUE TITLE
`__has_builtin(__debugbreak)` does not exist in code nature, what is this?

### ISSUE THREAD

**Issue by Challanger524** [nemequ/portable-snippets#51]
https://github.com/nemequ/portable-snippets/blob/84abba93ff3d52c87e08ba81de1cc6615a42b72e/debug-trap/debug-trap.h#L21-L22

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2514r0.html#_implementation_experience

**Comment by nemequ** [comment]
This is reaching back into my memory a bit, but `__debugbreak` is an MSVC intrinsic. I *think* some compilers based on clang which strive for MSVC compatibility (the new version of icl comes to mind, I forget what it's called) implement it, but it *may* have just been hopeful since `__debugbreak` does exactly what we want here.

**Comment by Challanger524** [comment]
`__has_builtin` is not present in `MSVC` so it is much more clear to test `__debugbreak()` presence via `__has_include(<intrin.h>)`, if compiler supports of course

```c++
#if __has_include(<intrin.h>)
#  include <intrin.h>
#  define BREAKPOINT() __debugbreak()
#endif
```

> some compilers based on clang which strive for MSVC compatibility

that is a narrow range of (a single?) compiler(s)
