### ISSUE TITLE
Limit macros for unsigned values

### ISSUE THREAD

**Issue by jibsen** [nemequ/portable-snippets#6]
In `exact-int.h`, I believe the `limits.h` macros for unsigned values are `USHRT_MAX`, `UINT_MAX`, `ULONG_MAX`, and `ULLONG_MAX`.

Also, the LLONG versions are only (required to be) available in C99/C++11 and forward.

I think technically, you are not guaranteed that the signed integer types are two's complement, so they could theoretically not work as base for the fixed-width types. But this is pretty far out on the what-if scale.

**Comment by jibsen** [comment]
> Also, the LLONG versions are only (required to be) available in C99/C++11 and forward.

Actually I guess that won't be a problem.

**Comment by nemequ** [comment]
Hi Jørgen, thanks for the report :)

> In exact-int.h, I believe the limits.h macros for unsigned values are USHRT_MAX, UINT_MAX, ULONG_MAX, and ULLONG_MAX.

You're right; I noticed that last night when I was working on `atomic.h` and [fixed it](https://github.com/nemequ/portable-snippets/commit/730f0fb79d2855abed7dc8a2b534d54ba5d29fee#diff-a08742f283450320ce57575a9f95afe7).  FWIW, that path is tested on CI now.

>> Also, the LLONG versions are only (required to be) available in C99/C++11 and forward.

> Actually I guess that won't be a problem.

You're right.  I'm not really trying to stick to a specific version of the C standard, just provide exact-width types wherever possible… if the system doesn't have `LLONG_MIN/MAX` then that just means `long long`/`unsigned long long` isn't considered.

That said, it probably makes sense to guard the macros in case they're not defined.  Technically you can used undefined macros, but every compiler I know of emits a warning.  76fbe0d393ccbaf90458d491871d741287565356 should do the trick.

> I think technically, you are not guaranteed that the signed integer types are two's complement, so they could theoretically not work as base for the fixed-width types. But this is pretty far out on the what-if scale.

Yeah, I'm not sure what to do about that.  Too bad I can't just use `UINT64_MIN`.  Anyways, if someone bumps into a platform where it doesn't work I'd love to take a look at how this could be implemented, but without access to a system like that I'm not sure what I can do.  Hopefully putting this stuff in a central repo will help, since everyone using it can benefit from fixes.
